// app/fintech-challenges/page.js
import ChallengesOpportunities from "@/components/customized/challegesOpportunities";

export default function TelecommunicationChallengesPage() {
  const sections = [
    {
      title: "OTT services Competition",
      content:
        "There has been a great decrease in the revenue generation due to the inception of messaging apps, about 2.5 billion of the world population is using at least a single messaging app. OTT services are taking over the market by a storm.",
      imageUrl: "/assets/api.png",
    },
    {
      title: "IoT gear up",
      content:
        "Integration of IoT and its convergence in daily lives makes it necessary for businesses to adapt to the trend too. By the year 2020 it is expected that there would be about 21 Billion of the total connected devices, adding a lot of pressure on the telecom industry to adopt too.",
      imageUrl: "/assets/api.png",
    },
    {
      title: "Voice Revenue Decrement",
      content:
        "BJust like the texting services there has been a major reduction in the revenue generated by the voice callings. With VOIP and internet messaging businesses are prone to going down even more.",
      imageUrl: "/assets/api.png",
    },
    {
      title: "Developing 5G",
      content:
        "By the end of the year 2020, it is expected that we will get 5G. Just like 4G people will be more and more inclined to adopt important services such as AR/ VR, IoT. Thus, it is important for telecom businesses to gear up to facilitate nothing but high-end experiences to be 'the go-to service provider'.",
      imageUrl: "/assets/api.png",
    },
    {
      title: "Digital Analysis",
      content:
        "A swift digital transformation telecom services and solutions allowing you to build a key platform component for your users to track their digital technology footprint and empower your digital transformation with digital analysis.",
      imageUrl: "/assets/api.png",
    },
    {
      title: "IoT Technology",
      content:
        "Technology has become cheaper and more available to be used to boost your Telecom IT Solutions. It is now easier to create new services to deliver measurable business outcomes using IoT Technology for a 21st century business",
      imageUrl: "/assets/api.png",
    },
    {
      title: "Application Services",
      content:
        "Multiple application platforms that allow your users to perform their tasks in one go. Technology today is allowing businesses to bring a more unified approach in their solutions by using mobile app development services.",
      imageUrl: "/assets/api.png",
    },,
    {
      title: "ML and Artificial Intelligence Solutions",
      content:
        "Technology is bringing automation and advanced technology tools at your doorsteps allowing you to keep a close track on your process while providing your proven Telecom IT consulting and services to give you monitoring tools, knowledge base and reports.",
      imageUrl: "/assets/api.png",
    },
    ,
    {
      title: "Augmented Reality (AR)",
      content:
        "Augmented Reality will be an ultimate game changer and more involvement will be seen in empowering the digital industry. It will also hold a good position in business core operations allowing them to improvise functions such as troubleshooting, providing solutions and more.",
      imageUrl: "/assets/api.png",
    },
  ];

  return (
    <ChallengesOpportunities
      title="Challenges And Opportunities"
      sections={sections}
     
      imagePosition="right"
      backgroundColor=""
      textColor="text-gray-800"
    />
  );
}